Add helpers vars_exist and commands_exist

diff --git a/src/.bashlc.d/00_helpers b/src/.bashlc.d/00_helpers
--- a/src/.bashlc.d/00_helpers
+++ b/src/.bashlc.d/00_helpers
@@ -10,12 +10,28 @@ function is_m1 {
 }
 export -f is_m1
 
-function must_exist {
+function commands_exist {
+    local commands=$*
+    local ret=0
+    local command
+    for command in $commands
+    do
+        if ! type "$command" &>/dev/null
+        then
+            echo "$command: command not available" >&2
+            ret=$((ret+1))
+        fi
+    done
+    return $ret
+}
+export -f commands_exist
+
+function vars_exist {
     local ret=0
     local i
     for i in $@
     do
-        # use subshell so we test all values even if set -e
+        # use subshell so we test all values as failing :? will exit 1
         if ! (eval ": \${$i:?}")
         then
             ret=$((ret+1))
@@ -23,4 +39,4 @@ function must_exist {
     done
     return $ret
 }
-export -f must_exist
+export -f vars_exist
